export const GET_ALL_CONTACTS = 'GET_ALL_CONTACTS'
export const GET_ALL_CONTACTS_SUCCESS = 'GET_ALL_CONTACTS_SUCCESS'
export const RESET_ALL_CONTACTS = 'RESET_ALL_CONTACTS'
export const UPDATE_SEARCH_KEY = 'UPDATE_SEARCH_KEY'
export const UPDATE_ONLY_EVEN_KEY_FILTER = 'UPDATE_ONLY_EVEN_KEY_FILTER'
export const UPDATE_PAGE_NUMBER = 'UPDATE_PAGE_NUMBER'
export const INCREMENT_PAGE_NUMBER = 'INCREMENT_PAGE_NUMBER'
export const UPDATE_COUNTRY = 'UPDATE_COUNTRY'
export const AUTH_TOKEN =
  'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjU2MCwiZXhwIjoxNzI2NTY3MTc5LCJ0eXBlIjoiYWNjZXNzIiwidGltZXN0YW1wIjoxNjk1MDMxMTc5fQ.0y7NtuVDCvcPvmWbliMs1q02sov2oFC6u2Hi6H4A2W4'
export const DEFAULT_COMPANY_ID = 171
export const ALL_COUNTRIES = 0
export const COUNTRY_USA  = 226
export const DEFAULT_NO_GROUP_DUPLICATES = 1